// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ApiRest_EntityFramework;

#nullable disable

namespace ApiRest_EntityFramework.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20241212221209_Creacion")]
    partial class Creacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Practica_Api_Rest_Entity.Models.Equipo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("liga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("equipos");
                });

            modelBuilder.Entity("Practica_Api_Rest_Entity.Models.Jugador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("altura")
                        .HasColumnType("int");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int?>("idEquipo")
                        .HasColumnType("int");

                    b.Property<string>("nacionalidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("peso")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idEquipo");

                    b.ToTable("jugadores");
                });

            modelBuilder.Entity("Practica_Api_Rest_Entity.Models.Jugador", b =>
                {
                    b.HasOne("Practica_Api_Rest_Entity.Models.Equipo", "equipo")
                        .WithMany("jugadores")
                        .HasForeignKey("idEquipo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("equipo");
                });

            modelBuilder.Entity("Practica_Api_Rest_Entity.Models.Equipo", b =>
                {
                    b.Navigation("jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
